go-bdd/gobdd

context/context.go
features/http.feature
go.sum
gobdd.go
gobdd_test.go
step/func.go
testhttp/requests.go
testhttp/setup.go
testhttp_test.go

Fixes https://github.com/go-bdd/gobdd/issues/7

add testHTTP package

---

gobdd.go
reporter/fmt.go

Fixes https://github.com/go-bdd/gobdd/issues/26

Add tags to fmt report

---

context/context.go
context/get.go
context/getparam.go
features/http.feature
gen/ctxget.go
gen/ctxgetparam.go
go.mod
go.sum
reporter/fmt.go
testhttp/requests_test.go
testhttp/setup.go
testhttp_test.go

Add getting fetching request header

---

context/context.go
gobdd.go

Fixes https://github.com/go-bdd/gobdd/issues/23

add execution in parallel

---

.github/workflows/ci.yml
context/context.go
context/doc.go
context/get.go
context/get_test.go
gen.go
gen/ctxgen.go
gobdd.go
gobdd_test.go
steps.go
steps_test.go
testhttp/setup.go
testhttp_test.go

Fixes https://github.com/go-bdd/gobdd/issues/57
FYI @sagikazarmark

Add context

---

context/context.go
context/get_test.go
gen/ctxgen.go

Fixes https://github.com/go-bdd/gobdd/issues/55
FYI @sagikazarmark

Add GetError to the context

---

docs/_data/navigation.yml
docs/suite-options.md

Fixes https://github.com/go-bdd/gobdd/issues/71

Add docs about suite options

---

gobdd.go

Fixes #50
I would add tests and probably move scenario hooks from options to the suite itself in a subsequent PR.

Add context to scenario hooks

---

context/context.go
context/get.go
context/get_test.go
docs/context.md
docs/quick-start.markdown
gen/ctxgen.go
gobdd_test.go
testhttp/setup.go
testhttp_test.go

remove explicit panics from the context

---

context/context.go
docs/creating-steps.markdown
docs/quick-start.markdown
gobdd.go
gobdd_test.go
steps.go
steps_test.go
testhttp/setup.go
testhttp_test.go

replace errors with logging

---

README.md

Do you think there's more info needed in the readme?

Update README with some details about quick start and sample app

---

context/context.go
context/context_test.go
go.mod

Return no error if ctx.GetError returns nil

---

gobdd.go

Fixes #108
(See the test runs for details)

Add keyword before name

---

features/ignored_feature_tags.feature
gobdd.go
gobdd_test.go

fix issue with not ignoring whole features using tags

---

docs/context.md
docs/creating-steps.markdown
gobdd.go
gobdd_test.go

closes #118
partially addresses #121

Add step hooks

---

.golangci.yml
context.go
context_get.go
context_get_as_test.go
context_get_test.go
go.sum
gobdd_test.go

add context.GetAs()

---

docs/suite-options.md
gobdd.go
gobdd_test.go

Fixes https://github.com/go-bdd/gobdd/issues/135

use varadic func for WithTags and WithIgnoredTags #135

---

docs/context.md
gobdd.go
gobdd_test.go

Store Feature and Scenario in test context

---

docs/parameter-types.md
features/parameter-types.feature
gobdd.go
gobdd_test.go

fix: cannot have multiple parameter type on the same line (go-bdd#147)

---

.github/workflows/ci.yml
.golangci.yml
context.go
gobdd.go
gobdd_test.go
steps.go

Allow access to testing.T object without extracting it from context

feat: give access to testing.T directly
